import random

SONG_DATABASE = {
    'happy': [
        "Happy - Pharrell Williams",
        "Can't Stop The Feeling! - Justin Timberlake",
        "Best Day Of My Life - American Authors",
        "On Top Of The World - Imagine Dragons",
        "Shut Up and Dance - WALK THE MOON",
        "Good Life - OneRepublic",
        "Walking On Sunshine - Katrina & The Waves",
        "Firework - Katy Perry",
        "Uptown Funk - Mark Ronson ft. Bruno Mars",
        "I Gotta Feeling - Black Eyed Peas",
        "Sugar - Maroon 5",
        "Roar - Katy Perry",
        "Counting Stars - OneRepublic",
        "Wake Me Up - Avicii",
        "Party Rock Anthem - LMFAO",
        "Cheerleader - OMI",
        "Mr. Brightside - The Killers",
        "Don't Stop Believin' - Journey",
        "I'm Yours - Jason Mraz",
        "Good Time - Owl City & Carly Rae Jepsen",
        "Send Me On My Way - Rusted Root",
        "Geronimo - Sheppard",
        "Love On Top - Beyoncé",
        "Valerie - Mark Ronson ft. Amy Winehouse",
        "Dance Monkey - Tones and I",
        "Feel So Close - Calvin Harris",
        "Can't Hold Us - Macklemore & Ryan Lewis",
        "Shake It Off - Taylor Swift",
        "Shotgun - George Ezra",
        "Pompeii - Bastille",
        "Safe and Sound - Capital Cities",
        "La La La - Naughty Boy ft. Sam Smith",
        "Go Your Own Way - Fleetwood Mac",
        "Dog Days Are Over - Florence + The Machine",
        "Viva La Vida - Coldplay",
        "Budapest - George Ezra",
        "You Make My Dreams - Hall & Oates",
        "Put Your Records On - Corinne Bailey Rae",
        "Move Your Feet - Junior Senior",
        "Island In The Sun - Weezer",
        "Send My Love (To Your New Lover) - Adele",
        "Best Song Ever - One Direction",
        "Sunflower - Post Malone & Swae Lee",
        "Love Me Like You Do - Ellie Goulding",
        "Just The Way You Are - Bruno Mars",
        "Cake By The Ocean - DNCE",
        "We Found Love - Rihanna ft. Calvin Harris",
        "Treasure - Bruno Mars",
        "Call Me Maybe - Carly Rae Jepsen",
        "Dynamite - Taio Cruz",
        "Classic - MKTO",
        "Lush Life - Zara Larsson",
        "Stolen Dance - Milky Chance",
        "Electric Feel - MGMT",
        "Youngblood - 5 Seconds Of Summer",
        "Blinding Lights - The Weeknd",
        "Good as Hell - Lizzo",
        "Shivers - Ed Sheeran"
    ],
    'sad': [
        "Someone Like You - Adele",
        "Fix You - Coldplay",
        "Let Her Go - Passenger",
        "All I Want - Kodaline",
        "Skinny Love - Birdy",
        "The Night We Met - Lord Huron",
        "Say Something - A Great Big World & Christina Aguilera",
        "How To Save A Life - The Fray",
        "Yesterday - The Beatles",
        "Happier - Ed Sheeran",
        "Lost Boy - Ruth B",
        "Jealous - Labrinth",
        "Too Good At Goodbyes - Sam Smith",
        "Creep - Radiohead",
        "I Will Always Love You - Whitney Houston",
        "Everybody Hurts - R.E.M.",
        "Somebody That I Used To Know - Gotye ft. Kimbra",
        "Chasing Cars - Snow Patrol",
        "Stay With Me - Sam Smith",
        "Un-break My Heart - Toni Braxton",
        "Let It Go - James Bay",
        "Jar Of Hearts - Christina Perri",
        "My Immortal - Evanescence",
        "The A Team - Ed Sheeran",
        "Because Of You - Kelly Clarkson",
        "Dancing On My Own - Calum Scott",
        "Say You Love Me - Jessie Ware",
        "Tears Dry On Their Own - Amy Winehouse",
        "Love The Way You Lie - Eminem ft. Rihanna",
        "The Scientist - Coldplay",
        "Lost Without You - Freya Ridings",
        "What About Us - Pink",
        "Breathe Me - Sia",
        "With Or Without You - U2",
        "This Year's Love - David Gray",
        "Back To Black - Amy Winehouse",
        "See You Again - Wiz Khalifa ft. Charlie Puth",
        "Iris - Goo Goo Dolls",
        "Yesterday - Leona Lewis",
        "Hurt - Christina Aguilera",
        "Let Me Down Slowly - Alec Benjamin",
        "Wrecking Ball - Miley Cyrus",
        "Breakeven - The Script",
        "The One That Got Away - Katy Perry",
        "Bleeding Love - Leona Lewis",
        "Apologize - OneRepublic",
        "In The End - Linkin Park",
        "Lost - Michael Bublé",
        "All Of Me - John Legend",
        "Everybody's Fool - Evanescence",
        "Demons - Imagine Dragons",
        "Far Away - Nickelback",
        "A Thousand Years - Christina Perri",
        "Faded - Alan Walker",
        "Let Her Go - Passenger",
        "Someone You Loved - Lewis Capaldi",
        "Talking To The Moon - Bruno Mars"
    ],
    'relax': [
        "Weightless - Marconi Union",
        "Sunset Lover - Petit Biscuit",
        "Holocene - Bon Iver",
        "River Flows In You - Yiruma",
        "Bloom - The Paper Kites",
        "Let Her Go - Passenger",
        "Banana Pancakes - Jack Johnson",
        "Budapest - George Ezra",
        "Ophelia - The Lumineers",
        "Cherry Wine - Hozier",
        "Breathe - Télépopmusik",
        "Dreams - Fleetwood Mac",
        "Yellow - Coldplay",
        "Stay Alive - José González",
        "I See Fire - Ed Sheeran",
        "Home - Edward Sharpe & The Magnetic Zeros",
        "Lost In Japan - Shawn Mendes",
        "Ocean Eyes - Billie Eilish",
        "Somewhere Only We Know - Keane",
        "Shivers - Ed Sheeran",
        "Let It Go - James Bay",
        "First Day Of My Life - Bright Eyes",
        "Banana Boat Song - Harry Belafonte",
        "Put It All On Me - Ed Sheeran",
        "Better Together - Jack Johnson",
        "Gravity - John Mayer",
        "Cherry - Harry Styles",
        "Lost - Dermot Kennedy",
        "Beautiful People - Ed Sheeran",
        "Location - Khalid",
        "Waves - Dean Lewis",
        "Skinny Love - Bon Iver",
        "Rivers and Roads - The Head and the Heart",
        "From The Dining Table - Harry Styles",
        "Photograph - Ed Sheeran",
        "Somebody Else - The 1975",
        "Breezeblocks - alt-J",
        "Home - Michael Bublé",
        "Let Me Down Slowly - Alec Benjamin",
        "All I Want - Kodaline",
        "Sunflower - Rex Orange County",
        "Lost - Frank Ocean",
        "Coffee - Beabadoobee",
        "Best Part - Daniel Caesar ft. H.E.R.",
        "Cherry Wine - Hozier",
        "Tenerife Sea - Ed Sheeran",
        "Fire and Rain - James Taylor",
        "Fast Car - Tracy Chapman",
        "Lost Cause - Billie Eilish",
        "All Of Me - John Legend",
        "Falling - Harry Styles",
        "The Night We Met - Lord Huron",
        "Let Her Go - Passenger",
        "Budapest - George Ezra",
        "Stolen Dance - Milky Chance",
        "Orpheus - Sara Bareilles",
        "Cigarette Daydreams - Cage the Elephant"
    ],
    'rock': [
        "Bohemian Rhapsody - Queen",
        "Hotel California - Eagles",
        "Sweet Child O' Mine - Guns N' Roses",
        "Stairway To Heaven - Led Zeppelin",
        "Livin' On A Prayer - Bon Jovi",
        "Back In Black - AC/DC",
        "Smells Like Teen Spirit - Nirvana",
        "Don't Stop Believin' - Journey",
        "Highway to Hell - AC/DC",
        "Dream On - Aerosmith",
        "Wonderwall - Oasis",
        "Eye of the Tiger - Survivor",
        "Enter Sandman - Metallica",
        "Come Together - The Beatles",
        "Paint It Black - The Rolling Stones",
        "Free Fallin' - Tom Petty",
        "November Rain - Guns N' Roses",
        "American Idiot - Green Day",
        "Boulevard of Broken Dreams - Green Day",
        "Knocking On Heaven's Door - Guns N' Roses",
        "Born to Run - Bruce Springsteen",
        "Paranoid - Black Sabbath",
        "Another Brick In The Wall - Pink Floyd",
        "Whole Lotta Love - Led Zeppelin",
        "Money For Nothing - Dire Straits",
        "Jump - Van Halen",
        "Black - Pearl Jam",
        "Creep - Radiohead",
        "Zombie - The Cranberries",
        "Californication - Red Hot Chili Peppers",
        "Scar Tissue - Red Hot Chili Peppers",
        "Take Me Out - Franz Ferdinand",
        "Sex On Fire - Kings Of Leon",
        "Are You Gonna Be My Girl - Jet",
        "In The End - Linkin Park",
        "Numb - Linkin Park",
        "I Bet You Look Good On The Dancefloor - Arctic Monkeys",
        "Reptilia - The Strokes",
        "Mr. Brightside - The Killers",
        "Plug In Baby - Muse",
        "Time Is Running Out - Muse",
        "Seven Nation Army - The White Stripes",
        "My Hero - Foo Fighters",
        "The Pretender - Foo Fighters",
        "Sweet Dreams (Are Made of This) - Marilyn Manson",
        "Hysteria - Muse",
        "Radioactive - Imagine Dragons",
        "Believer - Imagine Dragons",
        "It's My Life - Bon Jovi",
        "The Middle - Jimmy Eat World",
        "Everlong - Foo Fighters",
        "Basket Case - Green Day",
        "Kryptonite - 3 Doors Down",
        "Drive - Incubus",
        "I Want To Break Free - Queen"
    ],
    'pop': [
        "Blinding Lights - The Weeknd",
        "Shape of You - Ed Sheeran",
        "Levitating - Dua Lipa",
        "Bad Guy - Billie Eilish",
        "Uptown Funk - Mark Ronson ft. Bruno Mars",
        "Can't Stop The Feeling! - Justin Timberlake",
        "Sorry - Justin Bieber",
        "Closer - The Chainsmokers ft. Halsey",
        "Cheap Thrills - Sia",
        "Firework - Katy Perry",
        "Teenage Dream - Katy Perry",
        "Love Me Like You Do - Ellie Goulding",
        "Call Me Maybe - Carly Rae Jepsen",
        "Havana - Camila Cabello ft. Young Thug",
        "Stitches - Shawn Mendes",
        "Perfect - Ed Sheeran",
        "Don't Start Now - Dua Lipa",
        "Dance Monkey - Tones and I",
        "Sunflower - Post Malone & Swae Lee",
        "Rockstar - Post Malone ft. 21 Savage",
        "Shallow - Lady Gaga & Bradley Cooper",
        "Watermelon Sugar - Harry Styles",
        "Adore You - Harry Styles",
        "Senorita - Shawn Mendes & Camila Cabello",
        "Physical - Dua Lipa",
        "Memories - Maroon 5",
        "Sugar - Maroon 5",
        "Locked Out Of Heaven - Bruno Mars",
        "Treasure - Bruno Mars",
        "Just The Way You Are - Bruno Mars",
        "Counting Stars - OneRepublic",
        "Pompeii - Bastille",
        "Shotgun - George Ezra",
        "Wake Me Up - Avicii",
        "Don't Let Me Down - The Chainsmokers ft. Daya",
        "Stay - Zedd & Alessia Cara",
        "Let Me Love You - DJ Snake ft. Justin Bieber",
        "No Tears Left To Cry - Ariana Grande",
        "Break Free - Ariana Grande ft. Zedd",
        "Thank U, Next - Ariana Grande",
        "7 Rings - Ariana Grande",
        "Happier - Marshmello ft. Bastille",
        "Closer To Me - Ellie Goulding",
        "Rise - Jonas Blue ft. Jack & Jack",
        "This Is What You Came For - Calvin Harris ft. Rihanna",
        "Wolves - Selena Gomez & Marshmello",
        "Love Yourself - Justin Bieber",
        "Blank Space - Taylor Swift",
        "Shake It Off - Taylor Swift",
        "Wildest Dreams - Taylor Swift",
        "Lush Life - Zara Larsson",
        "Symphony - Clean Bandit ft. Zara Larsson",
        "Beautiful People - Ed Sheeran ft. Khalid",
        "Don't Call Me Up - Mabel",
        "If I Can't Have You - Shawn Mendes",
        "Intentions - Justin Bieber ft. Quavo"
    ]
}

def recommend_song(mood_or_genre):
    key = mood_or_genre.lower()
    if key in SONG_DATABASE:
        return random.choice(SONG_DATABASE[key])
    else:
        return ("Sorry, I couldn't find a song for that mood/genre. "
                "Try 'happy', 'sad', 'relax', 'rock', or 'pop'.")

def chatbot():
    print("Hello! I'm your Song Bot 🎵")
    print("Tell me your mood or favorite genre (e.g., happy, sad, relax, rock, pop), and I'll recommend a song!")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ['exit', 'quit', 'bye']:
            print("Bot: Goodbye! Enjoy your music!")
            break
        song = recommend_song(user_input)
        print(f"Bot: {song}")

if __name__ == "__main__":
    chatbot()